In [14]:
SIZE = 15
NUM = 1

GRAY_ZERO = 0
YELLOW_ONE = 1
BLUE_ZERO = 2
RED_ZERO = 3

In [15]:
import numpy as np
def generate_base_maze(size):
    assert size % 2 == 1, "size must be odd"
    maze = np.zeros((size, size))
    
    for i in range(size):
        for j in range(size):
            if i % 2 == 1 and j % 2 == 1 and i < size - 1 and j < size - 1:
                maze[i][j] = 1
    
    return maze

In [16]:
print(generate_base_maze(SIZE))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
def generate_maze(base_maze):
    # soft copy base maze
    maze = base_maze.copy()
    
    # step 2: randomly choose a border 1
    while 
    n = np.random.choice(np.arange(1, SIZE - 1, 2))
    m = np.random.choice(np.arange(1, SIZE - 1, 2))
    maze[i * n][]
        